### ISSUE TITLE
Queued listeners fail

### ISSUE THREAD

**Issue by klimenttoshkov** [zerodahero/laravel-workflow#68]
Hi,

When calling queued listeners:
```
Typed property Symfony\Component\Workflow\Event\Event::$subject must not be accessed before initialization {"exception":"[object] (Error(code: 0): Typed property Symfony\\Component\\Workflow\\Event\\Event::$subject must not be accessed before initialization at /Users/sag/Documents/code/zz_api/vendor/symfony/workflow/Event/Event.php:48)
[stacktrace]
```

**Comment by klimenttoshkov** [comment]
Error occurs when using $event->getSubject();

Full stack trace:
```
#0 /Users/sag/Documents/code/zz_api/app/BulkSMS/Listeners/Vouchers/ExpireSubscriber.php(19): Symfony\\Component\\Workflow\\Event\\Event->getSubject()
#1 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(107): App\\BulkSMS\\Listeners\\Vouchers\\ExpireSubscriber->announceExpire(Object(ZeroDaHero\\LaravelWorkflow\\Events\\AnnounceEvent))
#2 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle(Object(Illuminate\\Foundation\\Application))
#3 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#5 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#8 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#9 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#10 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(119): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Events\\CallQueuedListener), false)
#12 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#13 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#14 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(121): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#15 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(69): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Events\\CallQueuedListener))
#16 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#17 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#18 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#19 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(329): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#20 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(126): Illuminate\\Queue\\Worker->runNextJob('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#21 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(110): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#22 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#23 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#25 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#28 /Users/sag/Documents/code/zz_api/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#29 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 /Users/sag/Documents/code/zz_api/vendor/symfony/console/Application.php(989): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /Users/sag/Documents/code/zz_api/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /Users/sag/Documents/code/zz_api/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /Users/sag/Documents/code/zz_api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /Users/sag/Documents/code/zz_api/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 {main}
"} 

```

**Comment by klimenttoshkov** [comment]
Hi,

This is critical break. Please review.

**Comment by zerodahero** [comment]
Property visibility is a bit weird for unserialize. I've pushed a fix into `develop`, let me know if that addresses this and I'll push a patch release.

**Comment by klimenttoshkov** [comment]
Now works fine. I thought it was something with __parent needed.

**Comment by klimenttoshkov** [comment]
Now works fine. I thought it was something with __parent needed.
